import { ArtistViewEntity } from '../types';

const ref = (id: string, name: string, displayName: string = name) => ({
  artistId: id,
  artistName: name,
  artistDisplayName: displayName,
  artistLogoImageUrl: null,
  artistMainImageUrl: null,
});

export const DUMMY_ARTISTS: ArtistViewEntity[] = [
  // ── aespa (group) ──
  {
    artistId: '1',
    artistName: 'aespa',
    artistDisplayName: '에스파',
    artistSubDisplayName: null,
    artistAbbreviatedName: 'aespa',
    artistLogoImageUrl: null,
    artistMainImageUrl: null,
    artistDescription: 'SM Entertainment 4인조 걸그룹',
    parentArtists: null,
    childArtists: [
      ref('2', 'Karina', '카리나'),
      ref('3', 'Giselle', '지젤'),
      ref('4', 'Winter', '윈터'),
      ref('5', 'Ningning', '닝닝'),
    ],
    createdAt: '2024-06-01T10:00:00Z',
    updatedAt: '2025-02-15T14:30:00Z',
  },
  {
    artistId: '2',
    artistName: 'Karina',
    artistDisplayName: '카리나',
    artistSubDisplayName: 'aespa',
    artistAbbreviatedName: null,
    artistLogoImageUrl: null,
    artistMainImageUrl: null,
    artistDescription: 'aespa 리더',
    parentArtists: [ref('1', 'aespa', '에스파')],
    childArtists: null,
    createdAt: '2024-06-01T10:05:00Z',
    updatedAt: '2025-01-20T09:00:00Z',
  },
  {
    artistId: '3',
    artistName: 'Giselle',
    artistDisplayName: '지젤',
    artistSubDisplayName: 'aespa',
    artistAbbreviatedName: null,
    artistLogoImageUrl: null,
    artistMainImageUrl: null,
    artistDescription: 'aespa 멤버',
    parentArtists: [ref('1', 'aespa', '에스파')],
    childArtists: null,
    createdAt: '2024-06-01T10:10:00Z',
    updatedAt: '2025-01-18T11:00:00Z',
  },
  {
    artistId: '4',
    artistName: 'Winter',
    artistDisplayName: '윈터',
    artistSubDisplayName: 'aespa',
    artistAbbreviatedName: null,
    artistLogoImageUrl: null,
    artistMainImageUrl: null,
    artistDescription: 'aespa 멤버',
    parentArtists: [ref('1', 'aespa', '에스파')],
    childArtists: null,
    createdAt: '2024-06-01T10:15:00Z',
    updatedAt: '2025-03-01T08:00:00Z',
  },
  {
    artistId: '5',
    artistName: 'Ningning',
    artistDisplayName: '닝닝',
    artistSubDisplayName: 'aespa',
    artistAbbreviatedName: null,
    artistLogoImageUrl: null,
    artistMainImageUrl: null,
    artistDescription: 'aespa 멤버',
    parentArtists: [ref('1', 'aespa', '에스파')],
    childArtists: null,
    createdAt: '2024-06-01T10:20:00Z',
    updatedAt: '2025-01-10T16:00:00Z',
  },

  // ── NCT 127 (independent top-level group) ──
  {
    artistId: '7',
    artistName: 'NCT 127',
    artistDisplayName: 'NCT 127',
    artistSubDisplayName: null,
    artistAbbreviatedName: '127',
    artistLogoImageUrl: null,
    artistMainImageUrl: null,
    artistDescription: 'SM Entertainment 보이그룹, 서울 기반',
    parentArtists: null,
    childArtists: [
      ref('10', 'Taeyong', '태용'),
      ref('11', 'Mark', '마크'),
      ref('12', 'Haechan', '해찬'),
    ],
    createdAt: '2024-07-10T09:00:00Z',
    updatedAt: '2025-02-20T10:00:00Z',
  },
  {
    artistId: '8',
    artistName: 'NCT Dream',
    artistDisplayName: 'NCT Dream',
    artistSubDisplayName: null,
    artistAbbreviatedName: 'Dream',
    artistLogoImageUrl: null,
    artistMainImageUrl: null,
    artistDescription: 'SM Entertainment 보이그룹',
    parentArtists: null,
    childArtists: [ref('11', 'Mark', '마크'), ref('12', 'Haechan', '해찬')],
    createdAt: '2024-07-10T09:30:00Z',
    updatedAt: '2025-02-22T12:00:00Z',
  },
  {
    artistId: '9',
    artistName: 'WayV',
    artistDisplayName: 'WayV',
    artistSubDisplayName: null,
    artistAbbreviatedName: 'WayV',
    artistLogoImageUrl: null,
    artistMainImageUrl: null,
    artistDescription: 'SM Entertainment 보이그룹, 중국 기반',
    parentArtists: null,
    childArtists: [ref('13', 'Xiaojun', '샤오쥔'), ref('14', 'Ten', '텐')],
    createdAt: '2024-07-10T10:00:00Z',
    updatedAt: '2025-01-05T15:00:00Z',
  },
  {
    artistId: '10',
    artistName: 'Taeyong',
    artistDisplayName: '태용',
    artistSubDisplayName: 'NCT 127',
    artistAbbreviatedName: null,
    artistLogoImageUrl: null,
    artistMainImageUrl: null,
    artistDescription: 'NCT 127 리더',
    parentArtists: [ref('7', 'NCT 127', 'NCT 127')],
    childArtists: null,
    createdAt: '2024-07-10T10:30:00Z',
    updatedAt: '2025-02-10T09:00:00Z',
  },
  {
    artistId: '11',
    artistName: 'Mark',
    artistDisplayName: '마크',
    artistSubDisplayName: 'NCT 127 / NCT Dream',
    artistAbbreviatedName: null,
    artistLogoImageUrl: null,
    artistMainImageUrl: null,
    artistDescription: 'NCT 127 & NCT Dream 멤버 (듀얼 멤버십)',
    parentArtists: [
      ref('7', 'NCT 127', 'NCT 127'),
      ref('8', 'NCT Dream', 'NCT Dream'),
    ],
    childArtists: null,
    createdAt: '2024-07-10T11:00:00Z',
    updatedAt: '2025-02-25T14:00:00Z',
  },
  {
    artistId: '12',
    artistName: 'Haechan',
    artistDisplayName: '해찬',
    artistSubDisplayName: 'NCT 127 / NCT Dream',
    artistAbbreviatedName: null,
    artistLogoImageUrl: null,
    artistMainImageUrl: null,
    artistDescription: 'NCT 127 & NCT Dream 멤버 (듀얼 멤버십)',
    parentArtists: [
      ref('7', 'NCT 127', 'NCT 127'),
      ref('8', 'NCT Dream', 'NCT Dream'),
    ],
    childArtists: null,
    createdAt: '2024-07-10T11:30:00Z',
    updatedAt: '2025-02-18T11:00:00Z',
  },
  {
    artistId: '13',
    artistName: 'Xiaojun',
    artistDisplayName: '샤오쥔',
    artistSubDisplayName: 'WayV',
    artistAbbreviatedName: null,
    artistLogoImageUrl: null,
    artistMainImageUrl: null,
    artistDescription: 'WayV 멤버',
    parentArtists: [ref('9', 'WayV', 'WayV')],
    childArtists: null,
    createdAt: '2024-07-10T12:00:00Z',
    updatedAt: '2025-01-08T10:00:00Z',
  },
  {
    artistId: '14',
    artistName: 'Ten',
    artistDisplayName: '텐',
    artistSubDisplayName: 'WayV',
    artistAbbreviatedName: null,
    artistLogoImageUrl: null,
    artistMainImageUrl: null,
    artistDescription: 'WayV 멤버',
    parentArtists: [ref('9', 'WayV', 'WayV')],
    childArtists: null,
    createdAt: '2024-07-10T12:30:00Z',
    updatedAt: '2025-01-12T13:00:00Z',
  },

  // ── IU (solo) ──
  {
    artistId: '20',
    artistName: 'IU',
    artistDisplayName: '아이유',
    artistSubDisplayName: null,
    artistAbbreviatedName: 'IU',
    artistLogoImageUrl: null,
    artistMainImageUrl: null,
    artistDescription: '솔로 아티스트',
    parentArtists: null,
    childArtists: null,
    createdAt: '2024-05-15T08:00:00Z',
    updatedAt: '2025-03-03T16:00:00Z',
  },

  // ── SEVENTEEN (group + units + direct members) ──
  {
    artistId: '30',
    artistName: 'SEVENTEEN',
    artistDisplayName: '세븐틴',
    artistSubDisplayName: null,
    artistAbbreviatedName: 'SVT',
    artistLogoImageUrl: null,
    artistMainImageUrl: null,
    artistDescription: 'Pledis Entertainment 13인조 보이그룹',
    parentArtists: null,
    childArtists: [
      // 유닛
      ref('31', 'SVT Hip-Hop Unit', '힙합팀'),
      ref('32', 'SVT Vocal Unit', '보컬팀'),
      ref('33', 'SVT Performance Unit', '퍼포먼스팀'),
      ref('34', 'BSS', '부석순'),
      // 직속 멤버
      ref('40', 'S.Coups', '에스쿱스'),
      ref('41', 'Jeonghan', '정한'),
      ref('42', 'Joshua', '조슈아'),
      ref('43', 'Jun', '준'),
      ref('44', 'Hoshi', '호시'),
      ref('45', 'Wonwoo', '원우'),
      ref('46', 'Woozi', '우지'),
      ref('47', 'The8', '디에잇'),
      ref('48', 'Mingyu', '민규'),
      ref('49', 'DK', '도겸'),
      ref('50', 'Seungkwan', '승관'),
      ref('51', 'Vernon', '버논'),
      ref('52', 'Dino', '디노'),
    ],
    createdAt: '2024-08-01T09:00:00Z',
    updatedAt: '2025-02-28T10:00:00Z',
  },

  // ── SVT Units ──
  {
    artistId: '31',
    artistName: 'SVT Hip-Hop Unit',
    artistDisplayName: '힙합팀',
    artistSubDisplayName: 'SEVENTEEN',
    artistAbbreviatedName: null,
    artistLogoImageUrl: null,
    artistMainImageUrl: null,
    artistDescription: 'SEVENTEEN 힙합 유닛',
    parentArtists: [ref('30', 'SEVENTEEN', '세븐틴')],
    childArtists: [
      ref('40', 'S.Coups', '에스쿱스'),
      ref('45', 'Wonwoo', '원우'),
      ref('48', 'Mingyu', '민규'),
      ref('51', 'Vernon', '버논'),
    ],
    createdAt: '2024-08-01T09:10:00Z',
    updatedAt: '2025-02-01T09:00:00Z',
  },
  {
    artistId: '32',
    artistName: 'SVT Vocal Unit',
    artistDisplayName: '보컬팀',
    artistSubDisplayName: 'SEVENTEEN',
    artistAbbreviatedName: null,
    artistLogoImageUrl: null,
    artistMainImageUrl: null,
    artistDescription: 'SEVENTEEN 보컬 유닛',
    parentArtists: [ref('30', 'SEVENTEEN', '세븐틴')],
    childArtists: [
      ref('46', 'Woozi', '우지'),
      ref('41', 'Jeonghan', '정한'),
      ref('42', 'Joshua', '조슈아'),
      ref('49', 'DK', '도겸'),
      ref('50', 'Seungkwan', '승관'),
    ],
    createdAt: '2024-08-01T09:20:00Z',
    updatedAt: '2025-02-05T11:00:00Z',
  },
  {
    artistId: '33',
    artistName: 'SVT Performance Unit',
    artistDisplayName: '퍼포먼스팀',
    artistSubDisplayName: 'SEVENTEEN',
    artistAbbreviatedName: null,
    artistLogoImageUrl: null,
    artistMainImageUrl: null,
    artistDescription: 'SEVENTEEN 퍼포먼스 유닛',
    parentArtists: [ref('30', 'SEVENTEEN', '세븐틴')],
    childArtists: [
      ref('44', 'Hoshi', '호시'),
      ref('43', 'Jun', '준'),
      ref('47', 'The8', '디에잇'),
      ref('52', 'Dino', '디노'),
    ],
    createdAt: '2024-08-01T09:30:00Z',
    updatedAt: '2025-02-03T14:00:00Z',
  },
  {
    artistId: '34',
    artistName: 'BSS',
    artistDisplayName: '부석순',
    artistSubDisplayName: 'SEVENTEEN',
    artistAbbreviatedName: 'BSS',
    artistLogoImageUrl: null,
    artistMainImageUrl: null,
    artistDescription: 'SEVENTEEN 스페셜 유닛 (BooSeokSoon)',
    parentArtists: [ref('30', 'SEVENTEEN', '세븐틴')],
    childArtists: [
      ref('44', 'Hoshi', '호시'),
      ref('49', 'DK', '도겸'),
      ref('50', 'Seungkwan', '승관'),
    ],
    createdAt: '2024-08-01T09:40:00Z',
    updatedAt: '2025-02-12T10:00:00Z',
  },

  // ── SVT Members ──
  // Hip-Hop Unit
  {
    artistId: '40',
    artistName: 'S.Coups',
    artistDisplayName: '에스쿱스',
    artistSubDisplayName: 'SEVENTEEN',
    artistAbbreviatedName: null,
    artistLogoImageUrl: null,
    artistMainImageUrl: null,
    artistDescription: 'SEVENTEEN 리더, 힙합팀',
    parentArtists: [
      ref('30', 'SEVENTEEN', '세븐틴'),
      ref('31', 'SVT Hip-Hop Unit', '힙합팀'),
    ],
    childArtists: null,
    createdAt: '2024-08-01T10:00:00Z',
    updatedAt: '2025-01-30T09:00:00Z',
  },
  {
    artistId: '41',
    artistName: 'Jeonghan',
    artistDisplayName: '정한',
    artistSubDisplayName: 'SEVENTEEN',
    artistAbbreviatedName: null,
    artistLogoImageUrl: null,
    artistMainImageUrl: null,
    artistDescription: 'SEVENTEEN 보컬팀',
    parentArtists: [
      ref('30', 'SEVENTEEN', '세븐틴'),
      ref('32', 'SVT Vocal Unit', '보컬팀'),
    ],
    childArtists: null,
    createdAt: '2024-08-01T10:10:00Z',
    updatedAt: '2025-01-28T11:00:00Z',
  },
  {
    artistId: '42',
    artistName: 'Joshua',
    artistDisplayName: '조슈아',
    artistSubDisplayName: 'SEVENTEEN',
    artistAbbreviatedName: null,
    artistLogoImageUrl: null,
    artistMainImageUrl: null,
    artistDescription: 'SEVENTEEN 보컬팀',
    parentArtists: [
      ref('30', 'SEVENTEEN', '세븐틴'),
      ref('32', 'SVT Vocal Unit', '보컬팀'),
    ],
    childArtists: null,
    createdAt: '2024-08-01T10:20:00Z',
    updatedAt: '2025-01-25T14:00:00Z',
  },
  {
    artistId: '43',
    artistName: 'Jun',
    artistDisplayName: '준',
    artistSubDisplayName: 'SEVENTEEN',
    artistAbbreviatedName: null,
    artistLogoImageUrl: null,
    artistMainImageUrl: null,
    artistDescription: 'SEVENTEEN 퍼포먼스팀',
    parentArtists: [
      ref('30', 'SEVENTEEN', '세븐틴'),
      ref('33', 'SVT Performance Unit', '퍼포먼스팀'),
    ],
    childArtists: null,
    createdAt: '2024-08-01T10:30:00Z',
    updatedAt: '2025-01-22T16:00:00Z',
  },
  {
    artistId: '44',
    artistName: 'Hoshi',
    artistDisplayName: '호시',
    artistSubDisplayName: 'SEVENTEEN',
    artistAbbreviatedName: null,
    artistLogoImageUrl: null,
    artistMainImageUrl: null,
    artistDescription: 'SEVENTEEN 퍼포먼스팀 리더, BSS 멤버',
    parentArtists: [
      ref('30', 'SEVENTEEN', '세븐틴'),
      ref('33', 'SVT Performance Unit', '퍼포먼스팀'),
      ref('34', 'BSS', '부석순'),
    ],
    childArtists: null,
    createdAt: '2024-08-01T10:40:00Z',
    updatedAt: '2025-02-08T09:00:00Z',
  },
  {
    artistId: '45',
    artistName: 'Wonwoo',
    artistDisplayName: '원우',
    artistSubDisplayName: 'SEVENTEEN',
    artistAbbreviatedName: null,
    artistLogoImageUrl: null,
    artistMainImageUrl: null,
    artistDescription: 'SEVENTEEN 힙합팀',
    parentArtists: [
      ref('30', 'SEVENTEEN', '세븐틴'),
      ref('31', 'SVT Hip-Hop Unit', '힙합팀'),
    ],
    childArtists: null,
    createdAt: '2024-08-01T10:50:00Z',
    updatedAt: '2025-01-15T10:00:00Z',
  },
  {
    artistId: '46',
    artistName: 'Woozi',
    artistDisplayName: '우지',
    artistSubDisplayName: 'SEVENTEEN',
    artistAbbreviatedName: null,
    artistLogoImageUrl: null,
    artistMainImageUrl: null,
    artistDescription: 'SEVENTEEN 보컬팀 리더, 프로듀서',
    parentArtists: [
      ref('30', 'SEVENTEEN', '세븐틴'),
      ref('32', 'SVT Vocal Unit', '보컬팀'),
    ],
    childArtists: null,
    createdAt: '2024-08-01T11:00:00Z',
    updatedAt: '2025-02-14T13:00:00Z',
  },
  {
    artistId: '47',
    artistName: 'The8',
    artistDisplayName: '디에잇',
    artistSubDisplayName: 'SEVENTEEN',
    artistAbbreviatedName: null,
    artistLogoImageUrl: null,
    artistMainImageUrl: null,
    artistDescription: 'SEVENTEEN 퍼포먼스팀',
    parentArtists: [
      ref('30', 'SEVENTEEN', '세븐틴'),
      ref('33', 'SVT Performance Unit', '퍼포먼스팀'),
    ],
    childArtists: null,
    createdAt: '2024-08-01T11:10:00Z',
    updatedAt: '2025-01-20T15:00:00Z',
  },
  {
    artistId: '48',
    artistName: 'Mingyu',
    artistDisplayName: '민규',
    artistSubDisplayName: 'SEVENTEEN',
    artistAbbreviatedName: null,
    artistLogoImageUrl: null,
    artistMainImageUrl: null,
    artistDescription: 'SEVENTEEN 힙합팀',
    parentArtists: [
      ref('30', 'SEVENTEEN', '세븐틴'),
      ref('31', 'SVT Hip-Hop Unit', '힙합팀'),
    ],
    childArtists: null,
    createdAt: '2024-08-01T11:20:00Z',
    updatedAt: '2025-02-26T08:00:00Z',
  },
  {
    artistId: '49',
    artistName: 'DK',
    artistDisplayName: '도겸',
    artistSubDisplayName: 'SEVENTEEN',
    artistAbbreviatedName: null,
    artistLogoImageUrl: null,
    artistMainImageUrl: null,
    artistDescription: 'SEVENTEEN 보컬팀, BSS 멤버',
    parentArtists: [
      ref('30', 'SEVENTEEN', '세븐틴'),
      ref('32', 'SVT Vocal Unit', '보컬팀'),
      ref('34', 'BSS', '부석순'),
    ],
    childArtists: null,
    createdAt: '2024-08-01T11:30:00Z',
    updatedAt: '2025-02-06T12:00:00Z',
  },
  {
    artistId: '50',
    artistName: 'Seungkwan',
    artistDisplayName: '승관',
    artistSubDisplayName: 'SEVENTEEN',
    artistAbbreviatedName: null,
    artistLogoImageUrl: null,
    artistMainImageUrl: null,
    artistDescription: 'SEVENTEEN 보컬팀, BSS 멤버',
    parentArtists: [
      ref('30', 'SEVENTEEN', '세븐틴'),
      ref('32', 'SVT Vocal Unit', '보컬팀'),
      ref('34', 'BSS', '부석순'),
    ],
    childArtists: null,
    createdAt: '2024-08-01T11:40:00Z',
    updatedAt: '2025-02-09T10:00:00Z',
  },
  {
    artistId: '51',
    artistName: 'Vernon',
    artistDisplayName: '버논',
    artistSubDisplayName: 'SEVENTEEN',
    artistAbbreviatedName: null,
    artistLogoImageUrl: null,
    artistMainImageUrl: null,
    artistDescription: 'SEVENTEEN 힙합팀',
    parentArtists: [
      ref('30', 'SEVENTEEN', '세븐틴'),
      ref('31', 'SVT Hip-Hop Unit', '힙합팀'),
    ],
    childArtists: null,
    createdAt: '2024-08-01T11:50:00Z',
    updatedAt: '2025-01-18T14:00:00Z',
  },
  {
    artistId: '52',
    artistName: 'Dino',
    artistDisplayName: '디노',
    artistSubDisplayName: 'SEVENTEEN',
    artistAbbreviatedName: null,
    artistLogoImageUrl: null,
    artistMainImageUrl: null,
    artistDescription: 'SEVENTEEN 퍼포먼스팀, 막내',
    parentArtists: [
      ref('30', 'SEVENTEEN', '세븐틴'),
      ref('33', 'SVT Performance Unit', '퍼포먼스팀'),
    ],
    childArtists: null,
    createdAt: '2024-08-01T12:00:00Z',
    updatedAt: '2025-01-14T11:00:00Z',
  },
];
