name: PR Title Check

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm ci
      - name: Check PR title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            design
            fix
            hotfix
            comment
            docs
            style
            refactor
            perf
            test
            init
            build
            ci
            chore
            rename
            remove
            revert
          requireScope: false
          subjectPattern: ^[a-z].+$
          subjectPatternError: |
            The subject must start with a lowercase letter and not end with a period.
          wip: false
          validateSingleCommit: false